

const data = {
	user: {
		_id: '2323434',
		username: 'test',
		email: 'test@test.com',
		password: 'test',
	},
	clients: [
		{
			_id: 1,
			clientName: 'Shahkam',
			AnydeskAddress: '973 326 772',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 2,
			clientName: 'IL Apparel Warehouse New',
			AnydeskAddress: '619 725 125',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 3,
			clientName: 'MG Apparel Warehouse',
			AnydeskAddress: '871 594 011',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 4,
			clientName: 'CBL',
			AnydeskAddress: '695 850 342',
			AnydeskPassword: '12qweASD',
			ServerIp: '172.16.1.83',
			ServerUsername: 'Administrator',
			ServerPassword: '1234@abcd',
			BackendLink: 'http://172.16.1.83:4005/api',
			FrontendLink: 'http://172.16.1.83:5000',
			FrontendUser: 'test',
			FrontendPassword: '12345',
		},
		{
			_id: 5,
			clientName: 'Liberty',
			AnydeskAddress: '445 771 774',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 6,
			clientName: 'US5',
			AnydeskAddress: '841 012 361',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 7,
			clientName: 'Artistic SQMS AM4',
			AnydeskAddress: '453 280 344',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 8,
			clientName: 'Sadaqat',
			AnydeskAddress: '226 439 470',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: 'Administrator',
			ServerPassword: 'Root.123',
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 9,
			clientName: 'Gul Ahmed',
			AnydeskAddress: 'rfid-server-12@ad',
			AnydeskPassword: 'Rfid@a123',
			ServerIp: null,
			ServerUsername: 'Admin',
			ServerPassword: 'Rfid@a123',
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 1,
			clientName: 'Shahkam',
			AnydeskAddress: '973 326 772',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 2,
			clientName: 'IL Apparel Warehouse New',
			AnydeskAddress: '619 725 125',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 3,
			clientName: 'MG Apparel Warehouse',
			AnydeskAddress: '871 594 011',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 4,
			clientName: 'CBL',
			AnydeskAddress: '695 850 342',
			AnydeskPassword: '12qweASD',
			ServerIp: '172.16.1.83',
			ServerUsername: 'Administrator',
			ServerPassword: '1234@abcd',
			BackendLink: 'http://172.16.1.83:4005/api',
			FrontendLink: 'http://172.16.1.83:5000',
			FrontendUser: 'test',
			FrontendPassword: '12345',
		},
		{
			_id: 5,
			clientName: 'Liberty',
			AnydeskAddress: '445 771 774',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 6,
			clientName: 'US5',
			AnydeskAddress: '841 012 361',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 7,
			clientName: 'Artistic SQMS AM4',
			AnydeskAddress: '453 280 344',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 8,
			clientName: 'Sadaqat',
			AnydeskAddress: '226 439 470',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: 'Administrator',
			ServerPassword: 'Root.123',
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 9,
			clientName: 'Gul Ahmed',
			AnydeskAddress: 'rfid-server-12@ad',
			AnydeskPassword: 'Rfid@a123',
			ServerIp: null,
			ServerUsername: 'Admin',
			ServerPassword: 'Rfid@a123',
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 1,
			clientName: 'Shahkam',
			AnydeskAddress: '973 326 772',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 2,
			clientName: 'IL Apparel Warehouse New',
			AnydeskAddress: '619 725 125',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 3,
			clientName: 'MG Apparel Warehouse',
			AnydeskAddress: '871 594 011',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 4,
			clientName: 'CBL',
			AnydeskAddress: '695 850 342',
			AnydeskPassword: '12qweASD',
			ServerIp: '172.16.1.83',
			ServerUsername: 'Administrator',
			ServerPassword: '1234@abcd',
			BackendLink: 'http://172.16.1.83:4005/api',
			FrontendLink: 'http://172.16.1.83:5000',
			FrontendUser: 'test',
			FrontendPassword: '12345',
		},
		{
			_id: 5,
			clientName: 'Liberty',
			AnydeskAddress: '445 771 774',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 6,
			clientName: 'US5',
			AnydeskAddress: '841 012 361',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 7,
			clientName: 'Artistic SQMS AM4',
			AnydeskAddress: '453 280 344',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 8,
			clientName: 'Sadaqat',
			AnydeskAddress: '226 439 470',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: 'Administrator',
			ServerPassword: 'Root.123',
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 9,
			clientName: 'Gul Ahmed',
			AnydeskAddress: 'rfid-server-12@ad',
			AnydeskPassword: 'Rfid@a123',
			ServerIp: null,
			ServerUsername: 'Admin',
			ServerPassword: 'Rfid@a123',
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 1,
			clientName: 'Shahkam',
			AnydeskAddress: '973 326 772',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 2,
			clientName: 'IL Apparel Warehouse New',
			AnydeskAddress: '619 725 125',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 3,
			clientName: 'MG Apparel Warehouse',
			AnydeskAddress: '871 594 011',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 4,
			clientName: 'CBL',
			AnydeskAddress: '695 850 342',
			AnydeskPassword: '12qweASD',
			ServerIp: '172.16.1.83',
			ServerUsername: 'Administrator',
			ServerPassword: '1234@abcd',
			BackendLink: 'http://172.16.1.83:4005/api',
			FrontendLink: 'http://172.16.1.83:5000',
			FrontendUser: 'test',
			FrontendPassword: '12345',
		},
		{
			_id: 5,
			clientName: 'Liberty',
			AnydeskAddress: '445 771 774',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 6,
			clientName: 'US5',
			AnydeskAddress: '841 012 361',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 7,
			clientName: 'Artistic SQMS AM4',
			AnydeskAddress: '453 280 344',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 8,
			clientName: 'Sadaqat',
			AnydeskAddress: '226 439 470',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: 'Administrator',
			ServerPassword: 'Root.123',
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 9,
			clientName: 'Gul Ahmed',
			AnydeskAddress: 'rfid-server-12@ad',
			AnydeskPassword: 'Rfid@a123',
			ServerIp: null,
			ServerUsername: 'Admin',
			ServerPassword: 'Rfid@a123',
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 1,
			clientName: 'Shahkam',
			AnydeskAddress: '973 326 772',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 2,
			clientName: 'IL Apparel Warehouse New',
			AnydeskAddress: '619 725 125',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 3,
			clientName: 'MG Apparel Warehouse',
			AnydeskAddress: '871 594 011',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 4,
			clientName: 'CBL',
			AnydeskAddress: '695 850 342',
			AnydeskPassword: '12qweASD',
			ServerIp: '172.16.1.83',
			ServerUsername: 'Administrator',
			ServerPassword: '1234@abcd',
			BackendLink: 'http://172.16.1.83:4005/api',
			FrontendLink: 'http://172.16.1.83:5000',
			FrontendUser: 'test',
			FrontendPassword: '12345',
		},
		{
			_id: 5,
			clientName: 'Liberty',
			AnydeskAddress: '445 771 774',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 6,
			clientName: 'US5',
			AnydeskAddress: '841 012 361',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 7,
			clientName: 'Artistic SQMS AM4',
			AnydeskAddress: '453 280 344',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 8,
			clientName: 'Sadaqat',
			AnydeskAddress: '226 439 470',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: 'Administrator',
			ServerPassword: 'Root.123',
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 9,
			clientName: 'Gul Ahmed',
			AnydeskAddress: 'rfid-server-12@ad',
			AnydeskPassword: 'Rfid@a123',
			ServerIp: null,
			ServerUsername: 'Admin',
			ServerPassword: 'Rfid@a123',
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 1,
			clientName: 'Shahkam',
			AnydeskAddress: '973 326 772',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 2,
			clientName: 'IL Apparel Warehouse New',
			AnydeskAddress: '619 725 125',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 3,
			clientName: 'MG Apparel Warehouse',
			AnydeskAddress: '871 594 011',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 4,
			clientName: 'CBL',
			AnydeskAddress: '695 850 342',
			AnydeskPassword: '12qweASD',
			ServerIp: '172.16.1.83',
			ServerUsername: 'Administrator',
			ServerPassword: '1234@abcd',
			BackendLink: 'http://172.16.1.83:4005/api',
			FrontendLink: 'http://172.16.1.83:5000',
			FrontendUser: 'test',
			FrontendPassword: '12345',
		},
		{
			_id: 5,
			clientName: 'Liberty',
			AnydeskAddress: '445 771 774',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 6,
			clientName: 'US5',
			AnydeskAddress: '841 012 361',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 7,
			clientName: 'Artistic SQMS AM4',
			AnydeskAddress: '453 280 344',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 8,
			clientName: 'Sadaqat',
			AnydeskAddress: '226 439 470',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: 'Administrator',
			ServerPassword: 'Root.123',
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 9,
			clientName: 'Gul Ahmed',
			AnydeskAddress: 'rfid-server-12@ad',
			AnydeskPassword: 'Rfid@a123',
			ServerIp: null,
			ServerUsername: 'Admin',
			ServerPassword: 'Rfid@a123',
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 1,
			clientName: 'Shahkam',
			AnydeskAddress: '973 326 772',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 2,
			clientName: 'IL Apparel Warehouse New',
			AnydeskAddress: '619 725 125',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 3,
			clientName: 'MG Apparel Warehouse',
			AnydeskAddress: '871 594 011',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 4,
			clientName: 'CBL',
			AnydeskAddress: '695 850 342',
			AnydeskPassword: '12qweASD',
			ServerIp: '172.16.1.83',
			ServerUsername: 'Administrator',
			ServerPassword: '1234@abcd',
			BackendLink: 'http://172.16.1.83:4005/api',
			FrontendLink: 'http://172.16.1.83:5000',
			FrontendUser: 'test',
			FrontendPassword: '12345',
		},
		{
			_id: 5,
			clientName: 'Liberty',
			AnydeskAddress: '445 771 774',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 6,
			clientName: 'US5',
			AnydeskAddress: '841 012 361',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 7,
			clientName: 'Artistic SQMS AM4',
			AnydeskAddress: '453 280 344',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 8,
			clientName: 'Sadaqat',
			AnydeskAddress: '226 439 470',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: 'Administrator',
			ServerPassword: 'Root.123',
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 9,
			clientName: 'Gul Ahmed',
			AnydeskAddress: 'rfid-server-12@ad',
			AnydeskPassword: 'Rfid@a123',
			ServerIp: null,
			ServerUsername: 'Admin',
			ServerPassword: 'Rfid@a123',
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 1,
			clientName: 'Shahkam',
			AnydeskAddress: '973 326 772',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 2,
			clientName: 'IL Apparel Warehouse New',
			AnydeskAddress: '619 725 125',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 3,
			clientName: 'MG Apparel Warehouse',
			AnydeskAddress: '871 594 011',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 4,
			clientName: 'CBL',
			AnydeskAddress: '695 850 342',
			AnydeskPassword: '12qweASD',
			ServerIp: '172.16.1.83',
			ServerUsername: 'Administrator',
			ServerPassword: '1234@abcd',
			BackendLink: 'http://172.16.1.83:4005/api',
			FrontendLink: 'http://172.16.1.83:5000',
			FrontendUser: 'test',
			FrontendPassword: '12345',
		},
		{
			_id: 5,
			clientName: 'Liberty',
			AnydeskAddress: '445 771 774',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 6,
			clientName: 'US5',
			AnydeskAddress: '841 012 361',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 7,
			clientName: 'Artistic SQMS AM4',
			AnydeskAddress: '453 280 344',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 8,
			clientName: 'Sadaqat',
			AnydeskAddress: '226 439 470',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: 'Administrator',
			ServerPassword: 'Root.123',
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 9,
			clientName: 'Gul Ahmed',
			AnydeskAddress: 'rfid-server-12@ad',
			AnydeskPassword: 'Rfid@a123',
			ServerIp: null,
			ServerUsername: 'Admin',
			ServerPassword: 'Rfid@a123',
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 1,
			clientName: 'Shahkam',
			AnydeskAddress: '973 326 772',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 2,
			clientName: 'IL Apparel Warehouse New',
			AnydeskAddress: '619 725 125',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 3,
			clientName: 'MG Apparel Warehouse',
			AnydeskAddress: '871 594 011',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 4,
			clientName: 'CBL',
			AnydeskAddress: '695 850 342',
			AnydeskPassword: '12qweASD',
			ServerIp: '172.16.1.83',
			ServerUsername: 'Administrator',
			ServerPassword: '1234@abcd',
			BackendLink: 'http://172.16.1.83:4005/api',
			FrontendLink: 'http://172.16.1.83:5000',
			FrontendUser: 'test',
			FrontendPassword: '12345',
		},
		{
			_id: 5,
			clientName: 'Liberty',
			AnydeskAddress: '445 771 774',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 6,
			clientName: 'US5',
			AnydeskAddress: '841 012 361',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 7,
			clientName: 'Artistic SQMS AM4',
			AnydeskAddress: '453 280 344',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: null,
			ServerPassword: null,
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 8,
			clientName: 'Sadaqat',
			AnydeskAddress: '226 439 470',
			AnydeskPassword: '12qweASD',
			ServerIp: null,
			ServerUsername: 'Administrator',
			ServerPassword: 'Root.123',
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
		{
			_id: 9,
			clientName: 'Gul Ahmed',
			AnydeskAddress: 'rfid-server-12@ad',
			AnydeskPassword: 'Rfid@a123',
			ServerIp: null,
			ServerUsername: 'Admin',
			ServerPassword: 'Rfid@a123',
			BackendLink: null,
			FrontendLink: null,
			FrontendUser: null,
			FrontendPassword: null,
		},
	],
};

/**
 * Gets the dummy response for the given request
 * @param {string} apiPath - the path of the request api
 * @param {object} [options] - the options object (if any) of the request
 * @returns {Promise}
*/
const dummyFetch = (apiPath, options) => new Promise(resolve => {

	const response = {
		headers: [],
		json: undefined,
	};

	if (apiPath === 'auth/login') {
		response.json = user;
		if (options.returnHeaders) {
			const list = [{ key: 'CSRF', value: '12345' }, { key: 'JWToken', value: 'ABC12345' }];
			response.headers = {
				list,
				keys: list.map(row => row.key),
				values: list.map(row => row.value),
				get: (key) => list.find(row => row.key === key)?.value,
			}
		}
	}
	if (apiPath.includes('Client') && (!options?.method || options.method.toLowerCase() === 'get')) {
		response.json = data.clients;
	}
	else if (options?.method === 'POST') {
		response.json = options.body;
	}
	else if (options?.method === 'PATCH') {
		response.json = options.body;
	}
	else if (options?.method === 'DELETE') {
		response.json = options.body;
	}

	if (!response.json) {
		throw new Error();
	}

	const resolveReturn = {
		headers: response.headers,
		json: () => new Promise(resolve => resolve(response.json)),
	};

	setTimeout(() => resolve(resolveReturn), 1000);

});


export default dummyFetch;